steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['bash', 'echo', '$$suchita-cloud-secrete']
  secretEnv: ['suchita-cloud-secrete']
availableSecrets:
  secretManager:
  - versionName: projects/business-transformers/secrets/suchita-cloud-secrete/versions/1
    env: 'suchita-cloud-secrete'

#
