steps:
- name: 'bash'
  args: [$$suchita-cloud-secrete]
  secretEnv: ['suchita-cloud-secrete']
availableSecrets:
 secretManager:
  - versionName: projects/business-transformers/secrets/suchita-cloud-secrete/versions/1
    env: 'suchita-cloud-secrete'
