steps:
- name: 'bash'
  args: ['echo', $mediaagility]
  secretEnv: ['suchita-cloud']
availableSecrets:
 secretManager:
  - versionName: projects/business-transformers/secrets/suchita-cloud-secrete/versions/latest
    env: 'suchita-cloud'
